[build]
builder = "railpack"
dockerfilePath = ""
buildCommand = "npm install && npm run build --workspace=@pulsemed/client-hippreservation"

[deploy]
startCommand = "node clients/hippreservation/server.js"
